### ISSUE TITLE
Rendelés most már Segítségkérés

### ISSUE THREAD

**Issue by RosiestSage** [RosiestSage/Xiaomi-projekt#1]
Légyszíves figyeljetek oda, hogy ha másoljátok a termék bemutató mintát, akkor a "megrendelés" gombot ne másoljátok, a rendelő oldal megszűnt és segítségkérő oldal lett belőke (de nem neveztem át a html-t rendelesről segítségkérésre, szerintem felesleges, ez ne zavarjon össze titeket).. Elvileg kitöröltem a gombokat is. Pulloljatok!

**Comment by VargaDaniel2007** [comment]
A Rendelést majd írd át segítségkérésre a főoldalon!

**Comment by RosiestSage** [comment]
megcsináltam
